name: CI
on: 
  push:
    branches:
      - 'main'
jobs:
  Build-app:
    name: Run the test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python vulnerable-flask-app.py &
      - name: Test curl
        run: curl http://127.0.0.1:8081/


      # Continous Deliver
      # - name: executing remote ssh commands using password
      #  uses: appleboy/ssh-action@v1.0.0
      #  with:
      #    host: ${{ secrets.HOST }}
      #    username: ${{ secrets.USERNAME }}
      #    password: ${{ secrets.PASSWORD }}
      #    port: ${{ secrets.PORT }}
      #    script: |
      #      REPO_URL=git@github.com:acdk2662/Vulnerable-Flask-App.git
      #      LIVE_DIR=/home/acdk/Vulnerable-Flask-App
      #      echo "Pulling repository live..."
      #      mkdir -p $LIVE_DIR
      #      cd $LIVE_DIR
      #      git init
      #      git remote add origin $REPO_URL
      #      git pull origin main
      #      bash /home/acdk/config/killApp.sh && python3 /home/acdk/Vulnerable-Flask-App/vulnerable-flask-app.py &
      #      echo "On Production"